### ISSUE TITLE
Transition: ContainerView#childViews

### ISSUE THREAD

**Issue by jamesarosen** [zendesk/ember.js#9]
In Ember 0.9, `ContainerView` has an array-like `childViews` property. In Ember 1.0, `ContainerView` _acts_ like an array itself.
- [ ] backport functionality to make `ContainerView` act like an array
- [ ] add a flag to warn/raise when accessing its `childViews`

**Comment by ebryn** [comment]
@jamesarosen and I discussed this and determined that it's not worth the effort/risk to backport the deprecation warning. Our plan will be to upgrade and disable the deprecation warnings on 1.0 until we have the time to fix our usages.
